import type { Metadata } from "next";
import Navigation from "../components/ui/navigation";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import { ThemeProvider } from "../context/themeContext";

// const inter = Inter({
//   variable: "--font-inter",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   display: "swap",
//   style: ["normal", "italic"],
//   preload: true,
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   display: "swap",
//   style: ["normal", "italic"],
//   preload: true,
//   subsets: ["latin"],
// });

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mba Chibueze",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          " antialised min-h-screen flex flex-col ",
          manrope.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          },
        )}
      >
        <ThemeProvider>
          <Navigation />
          <div className="background-gradient h-screen  ">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
